devices:
  - INFSW1A-EQ4LON
  - INFSW1B-EQ4LON
  - TRDSW1A-EQ4LON
  - TRDSW1B-EQ4LON
  - TRDSW2A-EQ4LON
  - TRDSW2B-EQ4LON
  - TIMESERVER1A-EQ4LON
  - TIMESERVER1B-EQ4LON
  - PTPSW1A-EQ4LON
  - PTPSW1B-EQ4LON
  - CONSOLE1A-EQ4LON
  - CONSOLE1B-EQ4LON
