devices:
  - INFSW1A-DCEMEA
  - INFSW1B-DCEMEA
  - TRDSW1A-DCEMEA
  - TRDSW1B-DCEMEA
  - TRDSW2A-DCEMEA
  - TRDSW2B-DCEMEA
  - TIMESERVER1A-DCEMEA
  - TIMESERVER1B-DCEMEA
  - PTPSW1A-DCEMEA
  - PTPSW1B-DCEMEA
  - CONSOLE1A-DCEMEA
  - CONSOLE1B-DCEMEA
